version: 2

project_name: poster

changelog:
  disable: true

builds:
  - id: poster
    main: ./cmd/poster
    binary: poster
    ldflags: >-
      -s -w
      -X github.com/mahmoudashraf93/poster/internal/cmd.version={{ .Tag }}
      -X github.com/mahmoudashraf93/poster/internal/cmd.commit={{ .ShortCommit }}
      -X github.com/mahmoudashraf93/poster/internal/cmd.date={{ .Date }}
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - windows_arm64

archives:
  - builds:
      - poster
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt
